server:
  port: 10216
  servlet:
    context-path: /baseDataelementManage
  session-timeout: 7200
  session:
    tracking-modes: cookie
spring:
  application:
    id: DSP-DATAELEMENT
    name: DSP-DATAELEMENT
    admin: true
    # rc文件服务内网地址
    inner_rcservice: http://10.110.26.178:8443/rcservice
    # rc文件服务外网地址
    outer_rcservice: http://10.110.26.178:8443/rcservice
    # 一些登录配置
    login: /login
    login.exclude.path: /,/index,/login,/logout,/error,/restapi/**,/direct/manage/**,/captcha,/getMenuData,/captcha,/loginStatus
    # 登录类型
    login.type: 0
    # 登录地址
    rootContext: http://localhost:4200/dsp-vatalog/#
    outRootContext: http://localhost:4200/dsp-vatalog/#
    # 单点登录地址
    ucenter: http://10.110.26.178:8443/ucenter/
    sso:
      code: ''
    version: 1.0
  # 环境配置
  profiles:
    active: dev
  # 指定配置文件位置
  config:
    location: classpath:config/
  # 判断rc文件服务地址参数
  innerIp:
    start: 127.
  bsp:
    root-organ-code: 200427114503
#    url: http://10.110.26.178:8443/bsp
#    url: http://127.0.0.1:8101/bsp
    url: http://192.168.3.233:8101/bsp
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.110.26.121:3326/dataelement_management?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: dataelement
    password: a4OFWj{2yV0_^z
  flyway:
    baseline-on-migrate: true
    enabled: false
  main:
    # 允许循环引用。Spring将尝试通过解决部分Bean的实例化来打破循环依赖。
    allow-circular-references: true
    banner-mode: off
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  redis:
    host: 10.110.26.187
    password: GuoJia2024PT?!
    port: 16379
  web:
    locale: zh_CN
dubbo:
  application:
    name: DSP-BASEDATAELEMENTMANAGE
  config-center:
    timeout: 10000
  protocol:
    name: dubbo
    payload: 104857600
    port: 20001
  registry:
    address: 10.110.26.187:20001
    protocol: zookeeper
    timeout: 200000
  scan:
    base-packages: com.inspur
filter:
  xss: (((%3D)|(=))[^\n]*((%27)|(')|(--)|(%3B)|(:)|(%23)|(#)))|(\w*((%27)|('))((%6F)|o|(%4F))((%72)|r|(%52)))|(exec((\s)|(%20))+(s|x)p\w+)|((<|%3c)/?(script|iframe|frame|body|img|STYLE))|(set-cookie)|(src=('|")javascript:)|(Content-\w+:)|(\r)|(\n)|(alert)|(\+)|(\=)|(select)|(sleep)|(delete)|(onmouseover)|(%0d%0a)
flyway:
  placeholderReplacement: false
http:
  mappers:
    json-pretty-print: false
    json-sort-keys: false
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.inspur.dsp.*.dbentity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
